version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devxp
    ports:
      - '5432:5432'
    volumes:
      - devxp_data:/var/lib/postgresql/data

  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION:-us-east-1}.amazonaws.com/devxp-app:latest
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    env_file:
      - /home/ec2-user/meu-app/apps/app/.env
    volumes:
      - /home/ec2-user/meu-app/prisma:/app/prisma:ro

volumes:
  devxp_data:
    name: docker_devxp_data
